trigger: none

name: 'parallel_task'
jobs:
  - job: 'parallel_task'
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      - group: KeyVault
      - group: ProductionEnvVars
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7.8'
          architecture: 'x64'
      
      - script: |
          sudo apt install libpq-dev
        displayName: 'Install libpq-dev'

      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install azureml.pipeline.steps
        displayName: 'Install requirements'
        
      - script: |
          python parallel_task.py
        displayName: 'batch prediction inference'
        env:
          TENANT_ID: $(TenantID)
          SPN_ID: $(SpnID)
          SPN_PASSWORD: $(SpnPassword)
          AML_WORKSPACE_NAME: $(AmlWorkspaceName)
          RESOURCE_GROUP: $(ResourceGroup)
          SUBSCRIPTION_ID: $(SubscriptionID)